#!/bin/bash

alias gco='git checkout'
alias gcb='git checkout -b'
alias gb='git branch'
alias gstat='git status'
alias gd='git diff'
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit -m'
alias gca='git commit --amend'
alias gcaf='git commit --amend --no-edit'
alias gp='git push'
alias gpf='git push -f'
alias gpu='git push -u'
alias gl='git log --oneline'
alias glp='git log --oneline --decorate --graph'
alias gsp='git stash pop'
alias nah='git reset --hard; git clean -df;'
